[project]
name = "contracts"
authors = []
description = "Smart contracts for the campaign platform"
telemetry = true

[contracts.campaigns]
path = "contracts/campaigns.clar"
depends_on = []

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
